// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Background.tsx";
import * as $$$$$$1 from "./sections/BackgroundWrapper.tsx";
import * as $$$$$$2 from "./sections/CustomFooter.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$5 from "./sections/ItWorks.tsx";
import * as $$$$$$6 from "./sections/LandingPage.tsx";
import * as $$$$$$7 from "./sections/Navbar.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Background.tsx": $$$$$$0,
    "site/sections/BackgroundWrapper.tsx": $$$$$$1,
    "site/sections/CustomFooter.tsx": $$$$$$2,
    "site/sections/Footer.tsx": $$$$$$3,
    "site/sections/Hero.tsx": $$$$$$4,
    "site/sections/ItWorks.tsx": $$$$$$5,
    "site/sections/LandingPage.tsx": $$$$$$6,
    "site/sections/Navbar.tsx": $$$$$$7,
    "site/sections/Theme/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
